Traceback (most recent call last):
  File "E:\all_works\iclr2025\AEL-P-SNE(1)\AEL-P-SNE/problems/dpp_ga/eval.py", line 229, in <module>
    sys.path.insert(0, "../../../")
    ^^^
NameError: name 'sys' is not defined
