0.38s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
c:\Users\haibi\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\_vendored\force_pydevd.py:18: UserWarning: incompatible copy of pydevd already imported:
 d:\anaconda3\envs\data\envs\py3.11\Lib\site-packages\pydevd_plugins\extensions\pydevd_plugin_omegaconf.py
  warnings.warn(msg + ':\n {}'.format('\n  '.join(_unvendored)))
[*] Running ...
[*] Dataset loaded: e:\all_works\iclr2025\AEL-P-SNE(1)\AEL-P-SNE/problems/tsp_constructive\dataset\train50_dataset.npy with 5 instances.
[*] Instance 0: 5.530159701359854
[*] Instance 1: 6.619812342994742
[*] Instance 2: 6.745873585961244
[*] Instance 3: 6.716168954752427
[*] Instance 4: 6.0469921754234885
[*] Average:
6.331801352098351
